name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm destruction of all infrastructure'
        required: true
        type: string

env:
  AWS_REGION: eu-west-2
  TF_VERSION: 1.11.2

jobs:
  terraform-destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest
    environment: production  # This adds a manual approval gate
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "Confirmation failed. You must type 'DESTROY' exactly to proceed."
          exit 1
        fi
        echo "Confirmation validated"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
          -backend-config="region=${{ env.AWS_REGION }}"

    - name: Terraform Destroy
      env:
        TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        echo "Destroying infrastructure..."
        terraform destroy -auto-approve
        echo "Terraform destroy completed successfully!"

    - name: Destroy Summary
      if: always()
      run: |
        echo "## Destroy Results" >> $GITHUB_STEP_SUMMARY
        if [ "${{ job.status }}" = "success" ]; then
          echo "**Infrastructure successfully destroyed.**" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Destroy failed!**" >> $GITHUB_STEP_SUMMARY
          echo "- Check logs above for error details." >> $GITHUB_STEP_SUMMARY
        fi
